### ISSUE TITLE
read_raw_temp() will "fail" with BME280_STANDBY_0p5 for high-rate conversion

### ISSUE THREAD

**Issue by jeffsf** [adafruit/Adafruit_Python_BME280#16]
`read_raw_temp()` blocks for the conversion-in-progress indication to drop before trying to read. While this may be appropriate for the BME280 "forced" mode, data is available at all times for "normal" mode, as far as I can discern from the data sheet and my experience.

In the case that high-rate operation is desired, `BME280_STANDBY_0p5` reduces the standby time between conversions to 0.5 ms. As a result, the use of `time.sleep(0.002)` will often "miss" the window between when the conversion is completed and another begins. What should be jitter of the conversion period itself, now can be several periods. In early testing, I was seeing delays that often were 100-300 ms with a conversion period of under 50 ms.

If anything, the check should probably be done on bit 0, the "im_update" flag. It probably should be done with a block read of the sensor data, as I imagine that the duration of the time that the data in the registers many not be valid is very short. As that is described as an "NVM" data copy, I'm not sure that it even impacts the sensor registers (see data sheet section 7.4.4).

Should the library ever be expanded to support "forced" mode directly (the ability to write the proper registers is not exposed in the current API) there would be a need to have a blocking read until the conversion is complete. Until that time, this blocking behavior is detrimental for high-rate sensing applications.

For anyone reading this, one work-around is subclass BME280 and override `read_raw_temp()` removing the blocking wait
```
        # while (self._device.readU8(BME280_REGISTER_STATUS) & 0x08):    # Wait for conversion to complete (TODO : add timeout)
        #     time.sleep(0.002)
```

**Comment by ladyada** [comment]
hiya - we're closing all PRs and deprecating this library. if you're up for testing if this still exists in the circuitpython library, please open an issue there and we'll fix it on that library as this one is no longer going to be supported
https://github.com/adafruit/Adafruit_CircuitPython_BME280
