### ISSUE TITLE
Python program for subscription and publication of BME280 Sensor in RPI 3 in MQTT broker

### ISSUE THREAD

**Issue by mkdthanga** [adafruit/Adafruit_Python_BME280#21]
Dear Friends,
I am doing a master project in IOT!
How can I Publish and subscribe RPI 3 -BME280 sensor data in MQTT broker using Python script??
I know the simple message subscription and publication python programs, but to publish BME 280 sensor data and subscribe the published data in MQTT protocol, I don't know. Could anyone help me with this issue?
Thanks in advance!

Regards,
Thangaraj

**Comment by ferazambuja** [comment]
Try
https://www.eclipse.org/paho/clients/c/
