### ISSUE TITLE
Example code mislabels t_fine output as "Timestamp"

### ISSUE THREAD

**Issue by peter9477** [adafruit/Adafruit_Python_BME280#4]
The Adafruit_BME280_Example.py code outputs the sensor.t_fine value with a label of "Timestamp", but from what I can tell this is actually a "fine temperature" value used in pressure and/or humidity compensation calculations. It doesn't appear to have anything to do with time and is probably of little value to anyone except in debugging. See for reference section 4.2.3 of the datasheet http://www.adafruit.com/datasheets/BST-BME280_DS001-10.pdf .

**Comment by microbuilder** [comment]
Fixed in https://github.com/adafruit/Adafruit_Python_BME280/commit/0c5024197fc736edae7f7342f852a99bff31182a
