### ISSUE TITLE
Humidity calculation uses 16384.8 instead of 16384.0

### ISSUE THREAD

**Issue by RigacciOrg** [adafruit/Adafruit_Python_BME280#5]
From what I can understand of the datasheet (6.2.3 Compensation formulas), it seems that there is a typo in the code: the value 16384.8 is used instead of 16384.0.

It produces a little error in the humidity value.

**Comment by microbuilder** [comment]
Fixed in https://github.com/adafruit/Adafruit_Python_BME280/commit/f73319a0a2c0c12284aaed040957c5fa3df5ae8a
