### ISSUE TITLE
Returns 0.00% humidity for BMP280

### ISSUE THREAD

**Issue by yglodt** [adafruit/Adafruit_Python_BME280#7]
Hi,

when running it on a Pi Zero with a BMP280 connected via i2c it returns 0.00 for humidity:
```
root@zero:~/Adafruit_Python_BME280# python Adafruit_BME280_Example.py 
Timestamp = 114731.000
Temp      = 22.409 deg C
Pressure  = 986.51 hPa
Humidity  = 0.00 %
```

Is there a way to get the humidity?

**Comment by ladyada** [comment]
BMP280 does not have a humidity sensor
https://www.adafruit.com/products/2651

**Comment by yglodt** [comment]
Thanks for enlightening, looks like I confused the BMP with the BME.
